name: flutter_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8

  intl: ^0.19.0 # Or the latest version
  get_it: ^8.0.3
  dio: ^5.8.0+1
  shared_preferences: 2.5.3


  bloc: ^9.0.0
  bloc_concurrency: ^0.3.0
  flutter_bloc: ^9.1.1
  dartx: ^1.2.0


  go_router: ^15.1.2
  freezed_annotation: ^3.0.0

  collection: ^1.19.1
  dart_scope_functions: ^1.0.0
  uuid: ^4.3.3
  crypto: ^3.0.6

  # connectivity
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^3.0.1
  json_annotation: ^4.9.0

  talker: ^4.8.3
  talker_dio_logger: ^4.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  flutter_localizations:
    sdk: flutter

  freezed: ^3.0.5

  build_runner: ^2.4.15
  flutter_gen_runner:

  bloc_test: ^10.0.0
  mocktail: ^1.0.0
  json_serializable: ^6.9.5


  # Packaging window app
  # flutter_distributor: ^0.5.1

flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_intl:
  enabled: true
